import type { Aircraft } from './types'

/**
 * PLACEHOLDER DATA -- not a simulation.
 *
 * A fixed roster of arrivals so the strip bay can be looked at, styled and
 * tested before any aircraft exist. Nothing here moves: positions,
 * altitudes and speeds are frozen, and no physics touches them.
 *
 * Day 1 replaces this file with the real world model. The strip bay does
 * not know the difference -- it consumes `Aircraft` records either way,
 * which is the whole point of defining the model before the simulation.
 *
 * The bay shows a DEMO badge while this is the source, so a static picture
 * is never mistaken for working traffic.
 */
export const DEMO_ROSTER: readonly Aircraft[] = [
  {
    callsign: 'BAW178',
    type: 'A320',
    wake: 'M',
    pos: { x: 14.2, y: 6.1 },
    altFt: 7000,
    hdg: 250,
    gsKts: 240,
    vsFpm: -1200,
    clearedHdg: 250,
    clearedAltFt: 5000,
    clearedSpdKts: 220,
    navMode: 'VECTOR',
    clearedApproach: null,
    originFix: 'LAM',
    trail: [],
    spawnedAt: 0,
  },
  {
    callsign: 'VIR45',
    type: 'B789',
    wake: 'H',
    pos: { x: 22.9, y: 10.5 },
    altFt: 12000,
    hdg: 245,
    gsKts: 270,
    vsFpm: 0,
    clearedHdg: null,
    clearedAltFt: 12000,
    clearedSpdKts: 250,
    navMode: 'HOLD',
    clearedApproach: null,
    originFix: 'LAM',
    trail: [],
    spawnedAt: 0,
  },
  {
    callsign: 'SWR318',
    type: 'A321',
    wake: 'M',
    pos: { x: 9.4, y: 0.4 },
    altFt: 3000,
    hdg: 270,
    gsKts: 180,
    vsFpm: -700,
    clearedHdg: null,
    clearedAltFt: 2500,
    clearedSpdKts: 160,
    navMode: 'GS_TRACKING',
    clearedApproach: '27R',
    originFix: 'BIG',
    trail: [],
    spawnedAt: 0,
  },
  {
    callsign: 'EZY812',
    type: 'A320',
    wake: 'M',
    pos: { x: 15.8, y: -3.2 },
    altFt: 4000,
    hdg: 300,
    gsKts: 210,
    vsFpm: -500,
    clearedHdg: 300,
    clearedAltFt: 3000,
    clearedSpdKts: 190,
    navMode: 'LOC_ARMED',
    clearedApproach: '27L',
    originFix: 'BIG',
    trail: [],
    spawnedAt: 0,
  },
  {
    callsign: 'UAE29',
    type: 'A388',
    wake: 'J',
    pos: { x: -3.3, y: 15.3 },
    altFt: 13000,
    hdg: 168,
    gsKts: 280,
    vsFpm: 0,
    clearedHdg: null,
    clearedAltFt: 13000,
    clearedSpdKts: 250,
    navMode: 'HOLD',
    clearedApproach: null,
    originFix: 'BNN',
    trail: [],
    spawnedAt: 0,
  },
  {
    callsign: 'AAL106',
    type: 'B77W',
    wake: 'H',
    pos: { x: 0.5, y: -9.9 },
    altFt: 8000,
    hdg: 350,
    gsKts: 250,
    vsFpm: -1500,
    clearedHdg: 20,
    clearedAltFt: 6000,
    clearedSpdKts: 230,
    navMode: 'VECTOR',
    clearedApproach: null,
    originFix: 'OCK',
    trail: [],
    spawnedAt: 0,
  },
]
